  import { parseBankData, parseJobList } from "./functions";

  // Consumer Form Variables
  export const steps = [
  {
    title: "General Guidelines for All liveness checks",
    description: `- Camera Positioning: Your face should be centered in the frame, and the camera should not be positioned too far or too close.
        - Lighting Considerations:
        -- For **darker_skin_tones**, ensure **ample**, **even_lighting** is present. Avoid backlighting.
        -- For **lighter_skin_tones**, avoid **excessive_lighting** which may cause a "blown-out" appearance.
        -- Avoid **direct_sunlight** or **overexposed_rooms**.
        -- If needed, make a **90-degree_turn** to adjust for more balanced lighting conditions.
        - Background Requirements: Your background should be **plain,_uncluttered,** and preferably **neutral-colored** (e.g., grey or off-white). Avoid high-contrast patterns or movement in the background.
      `,
  },
  {
    title: "1. Head Movement",
    description: `Purpose: Prevents static photo-based spoofing.
    Instructions:
    - Move your head **naturally** in the directions as instructed.
    - Do **not** jerk or barely move your head.
    - Ensure your face remains **visible_and_centered** throughout.
    - Avoid quick tilts, fast nods, or excessive turns.
    - Avoid hats, glasses, hijabs, burka or chaadar for business purposes, masks, and veils. 
    Follow these instructions for successful onboarding.
    `,
  },
  {
    "title": "2. Finger or Hand Movement",
    description:`Purpose: Prevents use of cutouts, videos, or overlays.
      Instructions:
      - Perform **natural-finger** or **hand-gestures** as instructed.
      - Keep your **hand_clear_of_your_face**.
      - Avoid sudden, jerky movements or completely still hands.
      - Ensure adequate lighting as described above.
      `
  },
  {
    title: "3. Mouth Movement",
    description: `Purpose: Confirms dynamic liveness by detecting lip movement.
    Instructions:
    - Follow on-screen instructions to move your mouth (e.g., smile, speak, or open/close).
    - Make **smooth,_visible_movements**.
    - Keep your mouth **centered_and_visible** during motion.
    - Perfect movement and proper lighting will lead to success.
    `,
  },
  {
    title: "Attempt Limit Policy",
    description: `- Users are allowed **2_to_5_attempts** per liveness detection session.
    - After **5_failed_attempts,_a_5-minute_timeout** is enforced before retry.
    - Post-timeout, the session will be **recycled** and restarted.
    All failed attempts are **logged_and_tracked** per user to improve monitoring and ensure transparency in security reporting.
    `,
  },
  {
    finally:`Please be sure to follow all instructions carefully for successful verification and enhanced user experience.
    `
  }
]
  export const consumerProgressTackers = [
      ['My PEDIGREE INFO'],
      ['Notice and Consent for Biometric'],
      ['Face Recognition'],
      ['Address'],
      ['Gender Identity Information'],
      ['Ethnicity Information'],
      ['My Neighbors Are'],
      ['Employment Information'],
      ['Protect Charge Cards'],
      ['Review & Edit'],
      ['How did you hear about Us?'],
  ];
  export const suffixOptions = [
  "Mr.",
  "Mrs.",
  "Ms.",
  "Miss",
  "Mx.",
  "Junior, Jr., J",
  "Senior, Sr., S",
  "II, 2nd",
  "III, 3rd",
  "IV, 4th",
  "V, 5th",
  "VI, 6th",
  "VII, 7th",
  "VIII, 8th",
  "IX, 9th",
  ];
  export const branchOfServiceOptions = [
  "Army",
  "Air Force",
  "Marines",
  "Navy",
  "Space Force"
  ];
  export const forbiddenSQLKeywords = [
  'SELECT','SELECT *', ' AS ', 'AS ', 'SELECT DISTINCT', 'SELECT INTO', 'SELECT TOP', 'FROM', 'WHERE', ' AND ', 'AND ', ' OR ','OR ',
  'BETWEEN', 'LIKE', ' IN ', 'IS NULL', 'IS NOT NULL',
  'CREATE', 'CREATE DATABASE', 'CREATE TABLE', 'CREATE INDEX', 'CREATE VIEW',
  'DROP', 'DROP DATABASE', 'DROP TABLE', 'DROP INDEX',
  'UPDATE', 'DELETE', 'ALTER TABLE',
  'COUNT', 'SUM', 'AVG', 'MIN', 'MAX', 'INSERT', 'VALUES','EXEC', 'EXECUTE', 'JOIN',
  'ADD', 'CONCAT', 'UNION', 'UNION ALL', 'GROUP BY', 'ORDER BY', 'HAVING',
  'LIMIT', 'OFFSET', 'FETCH', 'ROW_NUMBER', 'PARTITION BY', 'WITH', 'CTE', 'TEMPORARY',
  'TEMP', 'TRANSACTION', 'COMMIT', 'ROLLBACK', 'SAVEPOINT', 'LOCK', 'UNLOCK',
  'GRANT', 'REVOKE', 'ALTER USER', 'ALTER ROLE', 'CREATE USER', 'CREATE ROLE',
  'DROP USER', 'DROP ROLE', 'EXECUTE AS', 'REVERT', 'SET TRANSACTION ISOLATION LEVEL',
  'SET NAMES', 'SET CHARACTER SET', 'SET SQL_MODE', 'SET AUTOCOMMIT', 'SET FOREIGN_KEY_CHECKS',
  'SET SQL_SAFE_UPDATES', 'SET GLOBAL', 'SET SESSION', 'SHOW', 'DESCRIBE', 'EXPLAIN',
  'USE', 'USE DATABASE', 'USE SCHEMA', 'SHOW DATABASES', 'SHOW TABLES', 'SHOW COLUMNS',
  'SHOW INDEXES', 'SHOW CREATE TABLE', 'SHOW CREATE DATABASE', 'SHOW CREATE VIEW',
  'ALTER', 'NOT', 'NULL', 'TRUE', 'FALSE', 'CASE', 'WHEN', 'THEN', 'ELSE', 'END','IS',
  'LIKE', 'ILIKE', 'SIMILAR TO', 'REGEXP', 'RLIKE', 'EXISTS', 'ANY', 'SOME',
   'DISTINCT', 'UNIQUE', 'PRIMARY KEY', 'FOREIGN KEY', 'REFERENCES', 'CHECK',
  'UNIONALL', 'INTERSECT', 'EXCEPT', 'WITH ROLLUP', 'WITH CUBE',
  ];
  export const selfIdentityTodayOptions = [
    "Male",
    "Female",
    "Agender",
    "Bigender",
    "Bi-Sexual Accept Me A Female",
    "Bi-Sexual Accept Me A Male",
    "Butch",
    "Cisgender",
    "Gay Female",
    "Gay Male",
    "Gender Non-Conforming",
    "Genderfluid",
    "Genderqueer",
    "Intersex",
    "Lesbian",
    "Non-Binary",
    "Pangender",
    "Transgender Accept Me As A Female",
    "Transgender Accept Me As A Male",
    "Two-Spirit"
  ];
  export let populationGroups = [
    "PLAHNET52 (P52)",
    "Pacific Islander Americans",
    "LGBTQIA+",
    "African Americans",
    "Asian",
    "Asian Indians",
    "Alaska Natives",
    "Alaska Native Corporations",
    "Hasidic Jews",
    "Hispanic-Americans",
    "Native Americans",
    "Ex-Offenders",
    "Tribal entities 52 (5A’s & 2H’s)",
    "Muslim",
    "Eskimo",
    "Disabled",
    "White (EA)",
    "Basque",
    "Celtic peoples (Irish, Scots, Welsh)",
    "Estonians",
    "Finns",
    "Germanic peoples (Danes, Dutch, English, Germans, Icelanders, Norwegians, Swedes)",
    "Greeks",
    "Romance peoples (French, Italians, Portuguese, Spanish, Romanians)",
    "Slavic peoples (Belarusians, Bulgarians, Croats, Czechs, Poles, Russians, Serbians, Ukrainians)",
    "Decline",
    "Other"
  ];

  export const racesNeighbours = [
    "Empty house",
    "European American",
    "No House-raw empty lot; or I'm at the end apartment ",
    "P52",
  ];
  export const incomeAndSupportOptions = [
  "I am a single parent raising 3 or more children alone.",
  "I am a Man paying child support or alimony",
  "$0 USD to $30,000 USD",
  "$30,001 USD to $75,000 USD",
  "$75,001 USD to $125,000 USD",
  "$125,001 USD to $200,000 USD",
  "$200,001 USD to $250,000 USD",
  "$250,001 USD to $400,000 USD",
  "$400,001 USD to $1,000,000 USD",
  "Greater than $1,000,000 USD"
  ];
  export const referralSources = [
    "Friends / Family Word of Mouth",
    "Counselor / Bank Professional referral",
    "Yahoo!",
    "Google",
    "Bing",
    "YouTube",
    "Website Banners",
    "Advertisement on Clothing",
    "Advertisement received at home",
    "Advertisement at bank",
    "Advertisement at a store",
    "Advertisement at a health care place",
    "Advertisement in magazine",
    "Newspaper Editorial",
    "Radio",
    "Television",
    "E-mail ads",
    "Internet Blogs",
    "Other"
  ];

  // Merchant Form Variables
  export const businessTypes = [
  "C-Corp",
  "Contractorship",
  "Cooperative",
  "DBA",
  "LLC",
  "PC",
  "S-Corp",
  "Sole Proprietorship",
  "Non-profit 503(c)(?)"
];
 export const primaryLineOfBusinessOptions = [
  'Accommodation and Food Services',
  'Administrative and Support and Waste Management and Remediation Services',
  'Agriculture, Forestry, Fishing and Hunting',
  'Arts, Entertainment, and Recreation',
  'Construction',
  'Educational Services',
  'Finance and Insurance',
  'Health Care and Social Assistance',
  'Information',
  'Management of Companies and Enterprises',
  'Manufacturing',
  'Mining',
  'Other Services (except Public Administration)',
  'Professional, Scientific, and Technical Services',
  'Public Administration',
  'Real Estate Rental and Leasing',
  'Retail Trade',
  'Transportation and Warehousing',
  'Utilities',
  'Wholesale Trade'
];
export const numberOfEmployeesOptions = [
  "1-50",
  "50-500",
  "500-1000",
  "1000-5000",
  "5001-10000",
  "10000+" 
];
export const salesPerMonthOptions = [
  "$0 – $3,000",
  "$3,000 – $10,000",
  "$10,000 – $40,000",
  "$40,000 – $75,000",
  "$75,000 – $100,000",
  "$100,000+"
];
export const industries = [
  "Accommodation and Food Services",
  "Administrative and Support and Waste Management and Remediation Services",
  "Agriculture",
  "Arts, Entertainment and Recreation",
  "Communication",
  "Construction",
  "Educational Services",
  "Finance and Insurance",
  "Fishing, and Forestry",
  "Health Care and Social Assistance",
  "Hunting",
  "Information Technology",
  "Management of Companies (holding companies)",
  "Manufacturing",
  "Mining",
  "Other Services",
  "Professional, Scientific, and Technical Services",
  "Real-estate and Rental and Leasing",
  "Retail Trade",
  "Transportation and Warehousing",
  "Travel",
  "Utilities",
  "Utility Company",
  "Wholesale Trade"
];
export const posSystems = [
  "Aloha POS",
  "Agilysys (InfoGenesis)",
  "Block (formerly Square)",
  "Bottle POS",
  "CardConnect",
  "Clover",
  "eHopper POS",
  "Epicor",
  "Epos Now",
  "GoDaddy",
  "Helcim",
  "IntercomPlus",
  "Lavu",
  "Lightspeed",
  "LS Retail",
  "Micros",
  "NCR",
  "NEC Corp. of America",
  "NetSuite",
  "Odoo",
  "Olo",
  "Oracle's MICROS RES POS",
  "PayPal Zettle",
  "Pecan",
  "Petrosoft SmartPOS",
  "POS Nation",
  "Quickbooks POS",
  "Radiant Systems",
  "Retail Sales manager",
  "Revel Systems",
  "Sage 100",
  "Shopify",
  "Square",
  "SumUp",
  "SUSE Linux Enterprise Point-of-Service (SLEPOS)",
  "Tecnica POS",
  "Toast",
  "Toshiba",
  "TouchBistro",
  "Upserve POS",
  "Vagaro",
  "Vend by Lightspeed",
  "Verifone"
];

export const categories = [
  "Merchant",
  "Third Party Only",
  "Both Merchant & Third Party",
  "GAA Export Only"
];
export const acquiringBank = [
  "None",
  "Chase Paymentech",
  "PNC Merchant Services",
  "Adyen",
  "Bank of America Merchant Services",
  "Chase Merchant Services",
  "Elavon",
  "EVO Payments",
  "First Data",
  "FiServ",
  "Global Payment",
  "Intuit Payments",
  "isbank",
  "iZettle",
  "JPMorgan Chase & Co.",
  "Merrick Bank",
  "Moneris",
  "North American Bank",
  "Priority Payments",
  "TSYS",
  "Wells Fargo Merchant Services",
  "Worldpay"
];
export const paymentProcessors = [
  "None",
  "Adyen",
  "Chase Paymenttech",
  "PNC Merchant Services",
  "Amazon Pay",
  "Authorize.Net",
  "BofA",
  "Braintree",
  "Clover",
  "Elavon",
  "EVO Payments Inc.",
  "Fiserv",
  "Global Payments",
  "Helcim",
  "Merchant One",
  "Merrick Bank",
  "North American Bank",
  "Payment Depot Inc.",
  "PayPal",
  "Shopify",
  "Square",
  "Stax",
  "Stripe",
  "Wells Fargo",
  "Worldpay"
]
// FI Form Variables
export let bankJobTitles = [
  "Account Settlement and Recovery Manager - Consumer Loans",
"Account Settlement and Recovery Supervisor - Consumer Loans",
"Account Settlement Representative I - Consumer Loans",
"Account Settlement Representative II - Consumer Loans",
"Accountant I",
"Accountant II",
"Accountant III",
"Accountant IV",
"Accountant V",
"Accounting Assistant I",
"Accounting Assistant II",
"Accounting Assistant III",
"Accounting Assistant IV",
"Accounting Clerk I",
"Accounting Clerk II",
"Accounting Clerk III",
"Accounting Clerk IV",
"Accounting Executive",
"Accounting Operations Senior Manager",
"Accounting Operations Supervisor",
"Accounting Senior Manager",
"Accounting Supervisor",
"Accounting Support Specialist I",
"Accounting Support Specialist II",
"Accounting Support Specialist III",
"Accounts Payable Analyst I",
"Accounts Payable Analyst II",
"Accounts Payable Analyst III",
"Accounts Payable Clerk I",
"Accounts Payable Clerk II",
"Accounts Payable Clerk III",
"Accounts Payable Coordinator I",
"Accounts Payable Coordinator II",
"Accounts Payable Coordinator III",
"Accounts Payable Processor I",
"Accounts Payable Processor II",
"Accounts Payable Processor III",
"Accounts Payable Senior Manager",
"Accounts Payable Senior Supervisor",
"Accounts Payable Specialist I",
"Accounts Payable Specialist II",
"Accounts Payable Specialist III",
"Accounts Payable/Receivable Analyst I",
"Accounts Payable/Receivable Analyst III",
"Accounts Payable/Receivable Analyst IV",
"Accounts Payable/Receivable Clerk I",
"Accounts Payable/Receivable Clerk II",
"Accounts Payable/Receivable Clerk III",
"Accounts Payable/Receivable Operations Senior Manager",
"Accounts Payable/Receivable Operations Senior Supervisor",
"Accounts Payable/Receivable Processing Coordinator I",
"Accounts Payable/Receivable Processing Coordinator II",
"Accounts Payable/Receivable Processing Coordinator III",
"Accounts Payable/Receivable Senior Manager",
"Accounts Payable/Receivable Senior Supervisor",
"Accounts Payable/Receivable Specialist I",
"Accounts Payable/Receivable Specialist III",
"Accounts Payable/Receivable Specialist IV",
"Accounts Receivable Analyst I",
"Accounts Receivable Analyst II",
"Accounts Receivable Analyst III",
"Accounts Receivable Analyst IV",
"Accounts Receivable Clerk I",
"Accounts Receivable Clerk II",
"Accounts Receivable Clerk III",
"Accounts Receivable Coordinator I",
"Accounts Receivable Coordinator II",
"Accounts Receivable Coordinator III",
"Accounts Receivable Operations Senior Manager",
"Accounts Receivable Operations Senior Supervisor",
"Accounts Receivable Processor I",
"Accounts Receivable Processor II",
"Accounts Receivable Processor III",
"Accounts Receivable Senior Manager",
"Accounts Receivable Senior Supervisor",
"Accounts Receivable Specialist I",
"Accounts Receivable Specialist II",
"Accounts Receivable Specialist III",
"Accounts Receivable Specialist IV",
"Adjustment Clerk II",
"Agricultural Lending Officer",
"Agricultural Loan Officer",
"Analyst, Entry - Fraud Detection",
"Analyst, Experienced - Fraud Detection",
"Analyst, Senior - Fraud Detection",
"Anti-Money Laundering (AML) Director",
"AP Analyst I",
"AP Analyst II",
"AP Analyst III",
"AP Clerk Entry",
"AP Clerk Intermediate",
"AP Clerk Senior",
"AP Operations Senior Manager",
"AP Operations Senior Supervisor",
"AP/AR Analyst I",
"AP/AR Analyst III",
"AP/AR Analyst IV",
"AP/AR Clerk I",
"AP/AR Clerk II",
"AP/AR Clerk III",
"AP/AR Senior Manager",
"AP/AR Senior Supervisor",
"Appraisal Senior Manager",
"Appraiser I (Commercial Real Estate)",
"Appraiser II (Commercial Real Estate)",
"Appraiser III (Commercial Real Estate)",
"Appraiser IV (Commercial Real Estate)",
"AR Analyst I",
"AR Analyst II",
"AR Analyst III",
"AR Analyst IV",
"AR Clerk I",
"AR Clerk II",
"AR Clerk III",
"AR Senior Manager",
"AR Senior Supervisor",
"Asset Management Executive",
"Assistant Financial Controller",
"Assistant Treasurer",
"Associate, Entry -Fraud Prevention",
"Associate, Experienced -Fraud Prevention",
"Associate, Senior -Fraud Prevention",
"Audit and Business Controls Manager",
"Audit and Business Controls Specialist I",
"Audit and Business Controls Specialist II",
"Audit and Business Controls Specialist III",
"Audit and Business Controls Specialist IV",
"Audit Manager",
"Audit Operations Senior Supervisor",
"Audit Operations Supervisor",
"Audit/Compliance Manager",
"Auditing Manager",
"Auditing Senior Supervisor",
"Auditing Supervisor",
"Auditing Team Senior Supervisor",
"Auditing Team Supervisor",
"Auditor Internal Controls I",
"Auditor Internal Controls II",
"Auditor Internal Controls III",
"Auditor Internal Controls IV",
"Bank Compliance Analyst I",
"Bank Compliance Analyst II",
"Bank Compliance and Risk Specialist I",
"Bank Compliance and Risk Specialist II",
"Bank Compliance Assistant",
"Bank Compliance Coordinator",
"Bank Compliance Manager",
"Bank Compliance Officer",
"Bank Compliance Specialist I",
"Bank Compliance Specialist II",
"Bank Internal Auditor",
"Bank Regulatory Compliance Assistant",
"Bank Regulatory Compliance Officer",
"Bank Regulatory Compliance Specialist I",
"Bank Regulatory Compliance Specialist II",
"Bank Secrecy Act Director",
"Bank Secrecy Director",
"Banking & Commercial Loan Workout Manager",
"Banking Operations Manager",
"Banking Operations Senior Supervisor",
"Banking Regulatory Compliance Director",
"Banking Strategic Development Director",
"Banking Systems Productivity Executive",
"Billing and Collections Analyst I",
"Billing and Collections Analyst II",
"Billing and Collections Analyst III",
"Billing and Collections Analyst IV",
"Billing and Collections Clerk I",
"Billing and Collections Clerk II",
"Billing and Collections Clerk III",
"Billing and Collections Senior Manager",
"Billing and Collections Senior Supervisor",
"Billing and Payables Analyst I",
"Billing and Payables Analyst II",
"Billing and Payables Analyst III",
"Billing and Payables Clerk I",
"Billing and Payables Clerk II",
"Billing and Payables Clerk III",
"Billing and Payables Senior Manager",
"Billing and Payables Senior Supervisor",
"Bookkeeping Clerk I",
"Bookkeeping Clerk II",
"Bookkeeping Clerk III",
"Branch Review and Audit Assistant",
"Branch Review and Audit Specialist",
"BSA Director",
"Budget Analysis Senior Manager",
"Budget Analyst - Specialist/Project Lead",
"Budget Analyst I",
"Budget Analyst II",
"Budget Analyst III",
"Budget Analyst IV",
"Budget Analyst, Experienced",
"Budget Analyst, Junior",
"Budget Senior Manager",
"Budget Support Analyst I",
"Budget Support Analyst II",
"Budget Support Analyst III",
"Budget Support Analyst IV",
"Budgeting Operations Supervisor",
"Budgeting Supervisor",
"Business /Economic Development Representative I",
"Business /Economic Development Representative II",
"Business /Economic Development Representative III",
"Business /Economic Development Representative IV",
"Business Banking Cash Management Officer I",
"Business Banking Cash Management Officer II",
"Business Banking Service Representative I",
"Business Banking Service Team Lead",
"Business Development Officer - Affluent Clients",
"Business Development Officer (Select Customer)",
"Business Development Officer (Select Customer), Sr.",
"Business Development Senior Officer - Affluent Clients",
"Business Loan Processing Manager",
"Business Loan Processing Senior Clerk",
"Business Unit Controller",
"Business Unit Controller, Sr.",
"Business Unit Financial Controller",
"Business Unit Financial Controller, Sr.",
"Cash Management Executive",
"Cash Management Manager",
"Cash Management Officer I",
"Cash Management Officer II",
"Cash Management Service Representative",
"Cash Management Service Representative, Entry",
"Cash Management Service Supervisor",
"Cash Management Services Supervisor",
"Chief Accounting Officer",
"Chief Actuarial Executive",
"Chief Actuarial Officer",
"Chief Financial Analysis Executive",
"Chief Financial Planning and Analysis Executive",
"Chief FP & A Executive",
"Chief Life Underwriting Executive",
"Chief Risk Officer",
"Chief Technology Officer",
"Revolving credit analyst",
"Personal loan officer",
"Chief Financial Officer",
"Chief Underwriting Officer",
"Claims Manager, Senior",
"Claims Review and Settlement Senior Manager",
"Claims Service and Operations Senior Manager",
"Collateral Appraiser",
"Collateral Valuation Specialist",
"Collection Manager",
"Collection Supervisor",
"Collection/Recovery Manager",
"Collection/Recovery Representative, Entry - Consumer Loans",
"Collection/Recovery Representative, Experienced - Consumer Loans",
"Collection/Recovery Supervisor",
"Collections Clerk, Entry - Loans",
"Collections Clerk, Experienced - Loans",
"Collections Clerk, Senior - Loans",
"Collections Representative I",
"Collections Representative II",
"Collections Representative III",
"Collections Specialist Supervisor",
"Collections Specialist, Entry",
"Collections Specialist, Experienced",
"Collections Supervisor",
"Collector I",
"Collector II",
"Collector III",
"Commercial Credit Analysis Manager",
"Commercial Credit Analyst I",
"Commercial Credit Analyst II",
"Commercial Credit Analyst III",
"Commercial Lending Regional or Industry Segment Manager I",
"Commercial Lending Regional or Industry Segment Manager II",
"Commercial Lending Regional or Industry Segment Manager III",
"Commercial Loan Clerk",
"Commercial Loan Credit Analysis Manager",
"Commercial Loan Director",
"Commercial Loan Processing Manager",
"Commercial Loan Processor",
"Commercial Loan Restructuring and Workout Manager",
"Commercial Loan Senior Manager",
"Commercial Loan Workout Manager",
"Commercial Real Estate Appraiser I",
"Commercial Real Estate Appraiser II",
"Commercial Real Estate Appraiser III",
"Commercial Real Estate Appraiser IV",
"Commercial Real Estate Lending Assistant Manager",
"Commercial Real Estate Lending Manager",
"Commercial Real Estate Loan Assistant Manager",
"Commercial Real Estate Loan Manager",
"Community Development and Relations Representative I",
"Community Development and Relations Representative II",
"Community Development and Relations Representative III",
"Community Development and Relations Representative IV",
"Community Development Executive",
"Community Development Manager I",
"Community Development Manager II",
"Community Development Relationship Manager I",
"Community Development Relationship Manager II",
"Community Development Representative I",
"Community Development Representative II",
"Community Development Representative III",
"Community Development Representative IV",
"Compliance & Bank Secrecy Director",
"Compliance Analyst III",
"Compliance Analyst IV",
"Compliance Analyst V",
"Compliance Director",
"Compliance Documentation Coordinator",
"Compliance Documentation Senior Coordinator",
"Compliance Reporting Coordinator",
"Compliance Reporting Senior Coordinator",
"Compliance Specialist III",
"Compliance Specialist IV",
"Compliance Specialist V",
"Compliance Supervisor",
"Consumer Credit Director",
"Consumer Credit/Collections Analyst, Entry",
"Consumer Credit/Collections Analyst, Experienced",
"Consumer Credit/Collections Analyst, Senior",
"Consumer Lending Director",
"Consumer Loan Collection Manager",
"Consumer Loan Collection Senior Team Leader",
"Consumer Loan Collection Supervisor I",
"Consumer Loan Collection Supervisor II",
"Consumer Loan Collection Team Leader",
"Consumer Loan Collection/Recovery Manager",
"Consumer Loan Collection/Recovery Rep. I",
"Consumer Loan Collection/Recovery Rep. II",
"Consumer Loan Collection/Recovery Supervisor",
"Consumer Loan Collections Group Manager",
"Consumer Loan Collector I",
"Consumer Loan Collector II",
"Consumer Loan Collector III",
"Consumer Loan Collector, Entry",
"Consumer Loan Collector, Experienced",
"Consumer Loan Collector, Senior",
"Consumer Loan Compliance and Quality Auditor",
"Consumer Loan Compliance Auditing Manager",
"Consumer Loan Credit Analyst I",
"Consumer Loan Credit Analyst II",
"Consumer Loan Credit Analyst III",
"Consumer Loan Credit Manager",
"Consumer Loan Credit Supervisor I",
"Consumer Loan Credit Supervisor II",
"Consumer Loan Payment and Reconciliation Clerk",
"Consumer Loan Quality Assurance Auditor",
"Consumer Loan Quality Assurance Manager",
"Consumer Loan Servicing Senior Supervisor",
"Consumer Payment Processing Clerk",
"Controller",
"Corporate Cash Flow/Liquidity Administration Manager",
"Corporate Cash Management Manager",
"Corporate Compliance Director",
"Corporate Compliance Specialist III",
"Corporate Compliance Specialist IV",
"Corporate Compliance Specialist V",
"Corporate Compliance Supervisor",
"CRA Business Development Director",
"CRA Business Development Manager",
"Credit Analysis Manager",
"Credit Analyst I",
"Credit Analyst I - Lending",
"Credit Analyst II",
"Credit Analyst II - Lending",
"Credit Analyst III",
"Credit Analyst III - Lending",
"Credit and Collections Analyst I",
"Credit and Collections Analyst II",
"Credit and Collections Analyst III",
"Credit and Collections Manager",
"Credit and Collections Operations Manager",
"Credit and Collections Operations Supervisor",
"Credit and Collections Supervisor",
"Credit Application Review Clerk",
"Credit Application Review Senior Clerk",
"Credit Clerk",
"Credit Clerk, Sr.",
"Credit Manager",
"Credit Manager - Lending",
"Credit Risk Analysis Manager",
"Credit Senior Supervisor - Lending",
"Credit Supervisor - Lending",
"Credit/Past Due Collections Manager",
"Credit/Past Due Collections Supervisor",
"Customer Account Adjustments Clerk II",
"Customer Complaint Adjustments Clerk II",
"Delinquent Account Collections Representative I",
"Delinquent Account Collections Representative II",
"Delinquent Account Collections Representative III",
"Delinquent Account Collections Supervisor",
"Department Manager Fraud Prevention",
"Deputy Controller",
"Deputy Treasurer",
"Director of High Net Worth Client Banking",
"Entry Accountant",
"Entry Accounting Clerk",
"Entry Budget Analyst",
"Entry Commercial Credit Analyst",
"Entry Consumer Loan Processor",
"Entry Credit Analyst",
"Entry Fraud Detection Associate",
"Entry Fraud Prevention Analyst",
"Entry Fraud Prevention Associate",
"Entry Internal Auditor",
"Entry Level Accounts Payable Clerk",
"Entry Level Auditor",
"Entry Level Staff Accountant",
"Entry Treasury Analyst",
"Finance Senior Manager - Budgets",
"Financial Accountant I",
"Financial Accountant II",
"Financial Accountant III",
"Financial Accountant IV",
"Financial Analysis Manager",
"Financial Analysis Senior Manager",
"Financial Analysis Supervisor",
"Financial Analyst I - Budgets",
"Financial Analyst II - Budgets",
"Financial Analyst III - Budgets",
"Financial Analyst IV - Budgets",
"Financial and Accounting Systems Analyst I",
"Financial and Accounting Systems Analyst II",
"Financial and Accounting Systems Analyst III",
"Financial and Accounting Systems Analyst IV",
"Financial and Accounting Systems Analyst V",
"Financial and Accounting Systems Director",
"Financial and Accounting Systems Manager",
"Financial and Accounting Systems Senior Manager",
"Financial and Accounting Systems Supervisor",
"Financial Business Systems Analyst I",
"Financial Business Systems Analyst II",
"Financial Business Systems Analyst III",
"Financial Business Systems Analyst IV",
"Financial Business Systems Analyst V",
"Financial Business Systems Director",
"Financial Business Systems Manager",
"Financial Business Systems Senior Manager",
"Financial Business Systems Supervisor",
"Financial Control Director",
"Financial Control Senior Manager",
"Financial Controller",
"Financial Controller - Division VP",
"Financial Planning Analyst V",
"Financial Planning and Analysis Manager",
"Financial Planning and Analysis Senior Manager",
"Financial Planning and Analysis Supervisor",
"Financial Reporting Director",
"Financial Services Operations Manager I",
"Financial Services Operations Manager II",
"Financial Statements and Reporting Director",
"Financial Systems Analyst I",
"Financial Systems Analyst II",
"Financial Systems Analyst III",
"Financial Systems Analyst IV",
"Financial Systems Analyst V",
"Financial Systems Director",
"Financial Systems Manager",
"Financial Systems Senior Manager",
"Financial Systems Supervisor",
"Foreign Exchange Executive",
"Foreign Exchange Manager",
"Foreign Exchange Trading Manager",
"FP & A Analyst V",
"FP & A Manager",
"FP & A Senior Manager",
"FP & A Supervisor",
"Fraud Detection Associate I",
"Fraud Detection Associate II",
"Fraud Detection Associate III",
"Fraud Detection Supervisor",
"Fraud Monitoring and Detection Specialist I",
"Fraud Monitoring and Detection Specialist II",
"Fraud Monitoring and Detection Specialist III",
"Fraud Monitoring and Detection Supervisor",
"Fraud Prevention Analysis Team Leader",
"Fraud Prevention Analyst I",
"Fraud Prevention Analyst II",
"Fraud Prevention Analyst III",
"Fraud Prevention Associate I",
"Fraud Prevention Associate II",
"Fraud Prevention Manager",
"Fraud Prevention Senior Manager",
"Fraud Prevention Specialist I",
"Fraud Prevention Specialist II",
"Fraud Prevention Specialist III",
"Fraud Prevention Supervisor",
"Fraud Prevention Team Leader",
"Fraud Program Analyst I",
"Fraud Program Analyst II",
"Fraud Program Analyst III",
"Fraud Program Manager",
"Fraud Program Senior Manager",
"Fraud Program Supervisor",
"Funding Executive",
"FX Trading Manager",
"General Accountant I",
"General Accountant II",
"General Accountant III",
"General Accountant IV",
"General Accountant V",
"Global Foreign Exchange Trading Executive",
"Head Commercial Real Estate Lending",
"Head of Accounting",
"Head of Auditing",
"Head of Branch Administration",
"Head of Collections",
"Head of Retail Banking",
"Head of Retail Banking Operations",
"Head of Risk Management",
"Head of Treasury",
"Insurance Litigation Attorney of Record",
"Intermediate Accountant",
"Intermediate Accounting Clerk",
"Intermediate Budget Analyst",
"Intermediate Commercial Credit Analyst",
"Intermediate Consumer Loan Processor",
"Intermediate Credit Analyst",
"Intermediate Fraud Detection Associate",
"Intermediate Fraud Prevention Analyst",
"Intermediate Fraud Prevention Associate",
"Intermediate Internal Auditor",
"Intermediate Treasury Analyst",
"Internal Auditing Manager",
"Internal Auditing Senior Supervisor",
"Internal Auditing Supervisor",
"Internal Auditor I",
"Internal Auditor II",
"Internal Auditor III",
"Internal Auditor IV",
"Jr Accountant",
"Junior Accountant",
"Lending and Credit Executive",
"Loan /Bad Debt Recovery Representative I",
"Loan /Bad Debt Recovery Representative II",
"Loan Collection Administrative Clerk I",
"Loan Collection Administrative Clerk II",
"Loan Collection Administrative Clerk III",
"Loan Collection Call Auditor",
"Loan Collection Clerk I",
"Loan Collection Clerk II",
"Loan Collection Clerk III",
"Loan Collection Compliance Auditor",
"Loan Collection Quality Assurance Monitor",
"Loan Collections Specialist I",
"Loan Collections Specialist II",
"Loan Collections Specialist III",
"Loan Origination/ Processing Supervisor - Consumer",
"Loan Processing Assistant Manager",
"Loan Processing Supervisor",
"Loan Processor I",
"Loan Processor II",
"Loan Processor III",
"Loan Restructuring Officer",
"Loan Servicing Clerk I",
"Loan Servicing Clerk II",
"Loan Servicing Clerk III",
"Loan Servicing Manager",
"Loan Servicing Representative I - Consumer Loans",
"Loan Servicing Representative II - Consumer Loans",
"Loan Servicing Representative III - Consumer Loans",
"Loan Servicing Specialist I - Consumer Loans",
"Loan Servicing Specialist II - Consumer Loans",
"Loan Servicing Specialist III - Consumer Loans",
"Loan Underwriter I",
"Loan Underwriter II",
"Loan Underwriter III",
"Loan Underwriting Manager I",
"Loan Underwriting Manager II",
"Loan Underwriting Supervisor",
"Loan Workout Manager",
"Loan/Bad Debt Recovery Manager",
"Loan/Bad Debt Recovery Supervisor",
"Mortgage Lending Executive",
"Operational Risk Analyst I",
"Operational Risk Analyst II",
"Operational Risk Analyst III",
"Operational Risk Analyst IV",
"Operational Risk Analyst V",
"Operational Risk Management Director",
"Operational Risk Management Supervisor",
"Operational Risk Manager",
"Operational Risk Modeling Analyst I",
"Operational Risk Modeling Analyst II",
"Operational Risk Modeling Analyst III",
"Operational Risk Modeling Analyst IV",
"Operational Risk Modeling Analyst V",
"Operational Risk Modeling Manager",
"Operational Risk Modeling Senior Manager",
"Operational Risk Senior Manager",
"P/C Underwriting Director",
"Payables/Receivables/Billing Analyst I",
"Payables/Receivables/Billing Analyst III",
"Payables/Receivables/Billing Analyst IV",
"Payables/Receivables/Billing Clerk I",
"Payables/Receivables/Billing Clerk II",
"Payables/Receivables/Billing Clerk III",
"Payables/Receivables/Billing Senior Manager",
"Payables/Receivables/Billing Senior Supervisor",
"Payment Processor",
"Private Banking Director",
"Private Client Banking Director",
"Problem Loan Restructuring/Resolution Officer",
"Property Casualty Insurance Underwriting Director",
"Property Casualty Underwriting Director",
"Property Casualty Underwriting Executive",
"Real Estate Appraisal and Valuation Senior Manager",
"Real Estate Appraisal Senior Manager",
"Real Estate Appraiser/Assessor, Commercial",
"Regional Bank President",
"Regional Consumer Lending Director",
"Regional Retail Banking President",
"Regulatory Compliance Director",
"Regulatory Compliance Supervisor",
"Regulatory Reporting Coordinator",
"Regulatory Reporting Senior Coordinator",
"Reinsurance Director",
"Reinsurance Plan Director",
"Retail Banking Executive",
"Retail Banking Operations Executive",
"Retail Branch Staff Trainer",
"Retail Branch Trainer",
"Risk Analyst I",
"Risk Analyst II",
"Risk Analyst III",
"Risk Analyst IV",
"Risk Analyst V",
"Risk Management Director",
"Risk Management Supervisor",
"Risk Manager",
"Risk Modeling Analyst I",
"Risk Modeling Analyst II",
"Risk Modeling Analyst III",
"Risk Modeling Analyst IV",
"Risk Modeling Analyst V",
"Risk Modeling Manager",
"Risk Modeling Senior Manager",
"Senior Accountant",
"Senior Accounting Clerk",
"Senior Accounting Executive",
"Senior Auditor",
"Senior Budget Analyst",
"Senior Collections Specialist",
"Senior Commercial Credit Analyst",
"Senior Commercial Loan Processing Clerk",
"Senior Compliance Analyst",
"Senior Consumer Loan Processor",
"Senior Controller",
"Senior Credit Analyst",
"Senior Credit Officer",
"Senior Department Manager Fraud Prevention",
"Senior Director of Treasury",
"Senior Financial Accountant",
"Senior Fraud Detection Associate",
"Senior Fraud Prevention Analyst",
"Senior Fraud Prevention Associate",
"Senior General Ledger Accountant",
"Senior Internal Auditor",
"Senior Manager Budgeting and Financial Control",
"Senior Risk Manager",
"Senior Treasury Analyst",
"Senior Treasury Analyst -Project Lead",
"Senior Vice President of Audit",
"Senior Vice President of FP & A",
"Senior Vice President of Real Estate",
"Specialist /Project Lead Internal Auditor",
"Specialist Accountant",
"Specialist/Project Lead Accountant",
"Staff Accountant I",
"Staff Accountant II",
"Staff Accountant III",
"Staff Accountant IV",
"Staff Accountant V",
"Staff Internal Auditor I",
"Staff Internal Auditor II",
"Staff Internal Auditor III",
"Staff Internal Auditor IV",
"Strategic Risk Modeling Analyst I",
"Strategic Risk Modeling Analyst II",
"Strategic Risk Modeling Analyst III",
"Strategic Risk Modeling Analyst IV",
"Strategic Risk Modeling Analyst V",
"Strategic Risk Modeling Manager",
"Strategic Risk Modeling Senior Manager",
"Supervisor Budgeting and Financial Control",
"SVP of Accounting",
"SVP of Audit and Business Controls",
"SVP of Auditing",
"SVP of Commercial Real Estate Lending",
"SVP of Financial Analysis",
"SVP of Financial Planning and Analysis",
"SVP of Internal Auditing",
"SVP of Lending",
"SVP of Lending and Credit",
"SVP of Real Estate",
"SVP of Real Estate Operations",
"SVP of Real Estate Portfolio",
"SVP of Retail Banking",
"SVP of Treasury",
"SVP of Treasury Operations",
"Top Group Underwriting Executive",
"Top Retail Branch Administration Executive",
"Treasurer II",
"Treasurer III",
"Treasury Analyst I",
"Treasury Analyst II",
"Treasury Analyst III",
"Treasury Analyst IV",
"Treasury Analyst V",
"Treasury Assistant Manager",
"Treasury Operations Analyst I",
"Treasury Operations Analyst II",
"Treasury Operations Analyst III",
"Treasury Operations Analyst IV",
"Treasury Operations Analyst V",
"Treasury Operations Assistant Manager",
"Treasury Operations Senior Director",
"Treasury Operations Supervisor",
"Treasury Specialist I",
"Treasury Specialist II",
"Treasury Specialist III",
"Treasury Specialist IV",
"Treasury Specialist V",
"Treasury Supervisor",
"Vice President - Claims Litigation",
"Vice President of Accounting",
"Vice President of Asset Management",
"Vice President of Branch Administration",
"Vice President of Cash Management",
"Vice President of Collections",
"Vice President of Commercial Lending",
"Vice President of Community Outreach and Development",
"Vice President of Credit",
"Vice President of Credit and Collections",
"Vice President of Financial Systems",
"Vice President of Foreign Exchange",
"Vice President of FP & A",
"Vice President of Funding",
"Vice President of Life Underwriting",
"Vice President of Mortgage Lending",
"Vice President of Operational Risk Management",
"Vice President of Property Casualty Underwriting",
"Vice President of Retail Banking Operations",
"Vice President of Risk Management",
"Vice President of Underwriting",
"VP of Actuarial Operations",
"VP of Actuarial Services",
"VP of Asset Management",
"VP of Branch Administration",
"VP of Cash Management",
"VP of Claims Litigation",
"VP of Collections",
"VP of Community Development",
"VP of Corporate Investment",
"VP of Credit Analysis",
"VP of Credit and Collections",
"VP of Credit and Collections Administration",
"VP of Financial Analysis",
"VP of Financial and Accounting Systems",
"VP of Financial Business Systems",
"VP of Financial Planning and Analysis",
"VP of Financial Systems",
"VP of Foreign Exchange",
"VP of Foreign Exchange Administration",
"VP of Funding Administration",
"VP of Investment Trading",
"VP of Investments",
"VP of Life Insurance Underwriting",
"VP of Life Underwriting",
"VP of Mortgage Funding",
"VP of Mortgage Lending",
"VP of Property Casualty Underwriting",
"VP of Retail Banking Operations",
"VP of Risk Management",
"VP of Securities and Equity Research",
"VP of Treasury",
"VP of Treasury Operations",
"VP of Underwriting",
"VP of Underwriting Administration",
"Bank Credit Clerk",
"Bank Foreign-Exchange Dealer",
"Bank Teller",
"Bond Sales Manager",
"Bond Sales Officer",
"Bond Trading Manager",
"Branch Manager – Insurance",
"Branch Manager Trainee",
"Branch Manager",
"Branch Review Specialist",
"Branch Review Team Lead",
"Branch Service Representative I",
"Branch Service Representative Ii",
"Branch Service Representative Iii",
"Branch Service Specialist",
"Budget Analyst I",
"Budget Analyst Ii",
"Budget Analyst Iii",
"Budget Analyst Iv",
"Budgeting Supervisor I",
"Budgeting Supervisor Ii",
"Budgeting Supervisor Iii",
"Business Banking Development Officer I",
"Business Banking Manger I, Ii",
"Business Banking Manger Ii",
"Business Development Officer",
"Business Development Officer (Select Customer) Senior",
"Business Systems Executive",
"Business Systems Manager",
"Business Systems Officer",
"Cash Management Manger",
"Cash Management Officer I",
"Cash Management Service Manager",
"Cash Management Service Representative I",
"Cash Management Service Representative Ii",
"Cash Management Service Representative Iii",
"Cash Management Service Supervisor",
"Check Collections Manager",
"Check Processing Manager",
"Check Processor",
"Checking / Debit Card Business Manager",
"Chief Compliance Officer (CCO)",
"Chief Executive Officer (CEO)",
"Chief Financial Officer (CFO)",
"Chief Information Officer (CIO)",
"Chief Lending Officer, Client Services Representative",
"Chief Operating Officer (COO)",
"Chief Risk Officer (CRO)",
"Chief Technology Officer (CTO)",
"Collateral Appraiser I, Ii",
"Collateral Appraiser Ii",
"Collateral Manager",
"Collections Representative I",
"Collections Representative Ii",
"Collections Representative Iii",
"Commercial Credit Analyst I",
"Commercial Credit Analyst Ii",
"Commercial Credit Analyst Iii",
"Commercial Loan Officer",
"Float Manager",
"Floor Banker",
"Head Bank Teller",
"Loan Officer",
"Mortgage Originator",
"Mortgage Payment Processing Clerk",
"Mortgage Processor",
"Mortgage Underwriter",
"Operations",
"Personal Loan Officer"
]
bankJobTitles = [...new Set(bankJobTitles)]; // Remove duplicates
bankJobTitles = bankJobTitles.sort((a, b) => a.localeCompare(b)); // Sort alphabetically
export const financialInstitutionOptions = [
  { id: "acquirers", label: "Acquirers" },
  { id: "assetManagementCompany", label: "Asset Management Company" },
  { id: "bondBrokerageFirm", label: "Bond Brokerage Firm" },
  { id: "checkCashingCompany", label: "Check Cashing Company" },
  { id: "commercialBanks", label: "Commercial banks" },
  { id: "communityBank", label: "Community Bank" },
  { id: "communityDevelopmentFinancialInstitution", label: "Community Development Financial Institution" },
  { id: "creditUnion", label: "Credit Union" },
  { id: "discountBrokerageBonds", label: "Discount Brokerage Bonds" },
  { id: "discountBrokerageStocks", label: "Discount Brokerage Stocks" },
  { id: "faceAmountCertificateCompany", label: "Face Amount Certificate Company" },
  { id: "fullBrokerageBonds", label: "Full Brokerage Bonds" },
  { id: "fullBrokerageStocks", label: "Full Brokerage Stocks" },
  { id: "hedgeFunds", label: "Hedge Funds" },
  { id: "insuranceCompany", label: "Insurance Company" },
  { id: "internetBank", label: "Internet Bank" },
  { id: "investmentBank", label: "Investment Bank" },
  { id: "managementInvestmentCompany", label: "Management Investment Company" },
  { id: "mortgageBanks", label: "Mortgage Banks" },
  { id: "mutualBank", label: "Mutual Bank" },
  { id: "paydayLender", label: "Payday Lender" },
  { id: "savingsAndLoan", label: "Savings & Loan" },
  { id: "shadowBank", label: "Shadow Bank" },
  { id: "stockBrokerageFirm", label: "Stock Brokerage Firm" },
  { id: "titleCompany", label: "Title Company" },
  { id: "unitInvestmentTrusts", label: "Unit Investment Trusts (UIT)" }
];


// functions.js
export async function getFinancialInstitutionsData() {
  let response = await fetch('/national-by-name.xlsx');
  let blob = await response.blob();
  let data = await parseBankData(blob);
  let obj = {...data};
  response = await fetch('/thrifts-by-name.xlsx');
  blob = await response.blob();
  data = await parseBankData(blob);
  obj = {...obj, ...data};
  response = await fetch('/trust-by-name.xlsx');
  blob = await response.blob();
  data = await parseBankData(blob);
  obj = {...obj, ...data};
  return obj;
}
export async function getJobTitlesData() {
  let response = await fetch('/JobList.xlsx');
  let blob = await response.blob();
  return parseJobList(blob);
}
export const financialSizeOptions = [
    'Large - $1.16 Billion or greater', 
    'Intermediate - $ 290 Million - $1.16 Billion',
    'Small – less than $290 Million'
];
export const financialServices = [
  { label: "Alternative Investments", id: "alternative_investments" },
  { label: "Auto loans", id: "auto_loans" },
  { label: "Bonds", id: "bonds" },
  { label: "Business Banking Accounts", id: "business_banking_accounts" },
  { label: "Business Banking Loans", id: "business_banking_loans" },
  { label: "Car Insurance", id: "car_insurance" },
  { label: "Casualty Insurance", id: "casualty_insurance" },
  { label: "Checking account", id: "checking_account" },
  { label: "Commercial Appraisals", id: "commercial_appraisals" },
  { label: "Commercial Paper", id: "commercial_paper" },
  { label: "Commercial Real Estate Loans", id: "commercial_real_estate_loans" },
  { label: "Correspondence banking", id: "correspondence_banking" },
  { label: "Corporate Reorganizations", id: "corporate_reorganizations" },
  { label: "Credit cards", id: "credit_cards" },
  { label: "Death Insurance", id: "death_insurance" },
  { label: "Debit cards", id: "debit_cards" },
  { label: "Demand deposits", id: "demand_deposits" },
  { label: "Disability Insurance", id: "disability_insurance" },
  { label: "Equity Offerings", id: "equity_offerings" },
  { label: "Exchange Traded Funds (ETFs)", id: "etfs" },
  { label: "Fire Insurance", id: "fire_insurance" },
  { label: "Health Insurance", id: "health_insurance" },
  { label: "Initial Public Offerings (IPOs)", id: "ipos" },
  { label: "Institutional Client Broker", id: "institutional_client_broker" },
  { label: "Insurance products", id: "insurance_products" },
  { label: "Investment Banking", id: "investment_banking" },
  { label: "Mergers and Acquisitions Facilitator", id: "mna_facilitator" },
  { label: "Mortgage loans", id: "mortgage_loans" },
  { label: "Mutual Funds Closed-ended", id: "mutual_funds_closed" },
  { label: "Mutual Funds Open-ended", id: "mutual_funds_open" },
  { label: "Personal loans", id: "personal_loans" },
  { label: "Property Insurance", id: "property_insurance" },
  { label: "Public / Private Share Offerings", id: "public_private_share_offerings" },
  { label: "Residential Appraisals", id: "residential_appraisals" },
  { label: "Residential Real Estate Loans", id: "residential_real_estate_loans" },
  { label: "Savings accounts", id: "savings_accounts" },
  { label: "Stocks", id: "stocks" },
  { label: "SWIFT", id: "swift" },
  { label: "Tax Deferred Annuity", id: "tax_deferred_annuity" },
  { label: "Trading", id: "trading" },
  { label: "Underwriting Debit", id: "underwriting_debit" },
  { label: "Wealth advisor", id: "wealth_advisor" },
  { label: "Wire Transfers", id: "wire_transfers" }
];
export const transactionRanges = [
  "50,000+ transactions per day",
  "50,000 – 30,000 transactions per day",
  "30,000 – 10,000 transactions per day",
  "Less than 10,000 transactions per day"
];

// Government Form Variables
export const sectors = [
  "Border Surveillance",
  "Chemical Sector",
  "Commercial Facilities Sector",
  "Commercial Sector",
  "Critical Manufacturing Sector",
  "Dams Sector",
  "Defense Industrial Base Sector",
  "Emergency Services Sector",
  "Energy Sector",
  "Financial Services Sector",
  "Food and Agriculture Sector",
  "Government Facilities Sector",
  "Healthcare and Public Health Sector",
  "Homeland Security",
  "Information Technology Sector",
  "Materials, and Waste Sector",
  "Nuclear Reactors",
  "Transportation Systems Sector",
  "Waste and Wastewater Systems Sector",
  "Other"
];
export const federalAgencies = [
  "AbilityOne Commission",
  "Access Board",
  "Administration for Children and Families (ACF)",
  "Administration for Community Living (ACL)",
  "Administration for Native Americans (ANA)",
  "Administrative Conference of the United States (ACUS)",
  "Administrative Office of the U.S. Courts",
  "Advisory Council on Historic Preservation (ACHP)",
  "Africa Command",
  "African Development Foundation (USADF)",
  "Agency for Global Media",
  "Agency for Healthcare Research and Quality (AHRQ)",
  "Agency for International Development (USAID)",
  "Agency for Toxic Substances and Disease Registry (ATSDR)",
  "Agricultural Marketing Service (AMS)",
  "Agricultural Research Service (ARS)",
  "Agriculture Department (USDA)",
  "Agriculture Library (NAL)",
  "Air Force",
  "Air Force Reserve",
  "Alcohol and Tobacco Tax and Trade Bureau (TTB)",
  "Alcohol, Tobacco, Firearms and Explosives Bureau (ATF)",
  "Alhurra TV",
  "American Battle Monuments Commission (ABMC)",
  "AmeriCorps",
  "AmeriCorps Seniors",
  "Animal and Plant Health Inspection Service (APHIS)",
  "Antitrust Division",
  "Appalachian Regional Commission (ARC)",
  "Architect of the Capitol",
  "Archives, National Archives and Records Administration (NARA)",
  "Arctic Research Commission (USARC)",
  "Armed Forces Retirement Home (AFRH)",
  "Arms Control and International Security",
  "Army",
  "Army Corps of Engineers",
  "Arthritis, Musculoskeletal and Skin Diseases, National Institute of (NIAMS)",
  "Bankruptcy Courts",
  "Barry M. Goldwater Scholarship and Excellence in Education Foundation",
  "Bonneville Power Administration (BPA)",
  "Botanic Garden",
  "Bureau of Alcohol and Tobacco Tax and Trade (TTB)",
  "Bureau of Alcohol, Tobacco, Firearms and Explosives (ATF)",
  "Bureau of Consular Affairs",
  "Bureau of Consumer Financial Protection (CFPB)",
  "Bureau of Economic Analysis (BEA)",
  "Bureau of Engraving and Printing (BEP)",
  "Bureau of Indian Affairs (BIA)",
  "Bureau of Industry and Security (BIS)",
  "Bureau of International Labor Affairs (ILAB)",
  "Bureau of Justice Statistics (BJS)",
  "Bureau of Labor Statistics (BLS)",
  "Bureau of Land Management (BLM)",
  "Bureau of Ocean Energy Management (BOEM)",
  "Bureau of Prisons (FBOP)",
  "Bureau of Reclamation",
  "Bureau of Safety and Environmental Enforcement (BSEE)",
  "Bureau of the Census",
  "Bureau of the Fiscal Service",
  "Bureau of Transportation Statistics (BTS)",
  "Capitol Police",
  "Capitol Visitor Center",
  "Career, Technical, and Adult Education, Office of (OCTAE)",
  "Census Bureau",
  "Center for Food Safety and Applied Nutrition (CFSAN)",
  "Center for Nutrition Policy and Promotion (CNPP)",
  "Center for Parent Information and Resources (CPIR)",
  "Centers for Disease Control and Prevention (CDC)",
  "Centers for Medicare and Medicaid Services (CMS)",
  "Central Command (CENTCOM)",
  "Central Intelligence Agency (CIA)",
  "Chemical Safety Board (CSB)",
  "Chief Acquisition Officers Council (CAOC)",
  "Chief Financial Officers Council (CFO)",
  "Chief Human Capital Officers (CHCO) Council",
  "Chief Information Officers Council (CIO)",
  "Child Support Enforcement, Office of (OCSS)",
  "Circuit Courts of Appeal",
  "Citizens' Stamp Advisory Committee (CSAC)",
  "Citizenship and Immigration Services (USCIS)",
  "Civil Rights Division, Department of Justice",
  "Civil Rights, Department of Education Office of (OCR)",
  "Civil Rights, Department of Health and Human Services Office for (OCR)",
  "Coast Guard (USCG)",
  "Commerce Department (DOC)",
  "Commission of Fine Arts",
  "Commission on Civil Rights (USCCR)",
  "Commission on International Religious Freedom (USCIRF)",
  "Commission on Presidential Scholars",
  "Commission on Security and Cooperation in Europe (Helsinki Commission)",
  "Committee on Foreign Investment in the United States (CFIUS)",
  "Commodity Futures Trading Commission (CFTC)",
  "Community Oriented Policing Services (COPS)",
  "Community Planning and Development (CPD)",
  "Comptroller of the Currency, Office of (OCC)",
  "Congress—U.S. House of Representatives",
  "Congress—U.S. Senate",
  "Congressional Budget Office (CBO)",
  "Congressional Research Service (CRS)",
  "Congressional Workplace Rights, Office of (OCWR)",
  "Consular Affairs, Bureau of",
  "Consumer Financial Protection Bureau (CFPB)",
  "Consumer Product Safety Commission (CPSC)",
  "Coordinating Council on Juvenile Justice and Delinquency Prevention",
  "Copyright Office",
  "Corps of Engineers",
  "Council of Economic Advisers (CEA)",
  "Council of the Inspectors General on Integrity and Efficiency (CIGIE)",
  "Council on Environmental Quality (CEQ)",
  "Court of Appeals for the Armed Forces",
  "Court of Appeals for the Federal Circuit",
  "Court of Appeals for Veterans Claims",
  "Court of Federal Claims",
  "Court of International Trade",
  "Court Services and Offender Supervision Agency for the District of Columbia (CSOSA)",
  "Customs and Border Protection (CBP)",
  "Cyber Command",
  "Cybersecurity and Infrastructure Security Agency (CISA)",
  "Debt and Claims Management Center",
  "Defense Advanced Research Projects Agency (DARPA)",
  "Defense Commissary Agency",
  "Defense Contract Audit Agency (DCAA)",
  "Defense Contract Management Agency (DCMA)",
  "Defense Counterintelligence and Security Agency (DCSA)",
  "Defense Department (DOD)",
  "Defense Finance and Accounting Service (DFAS)",
  "Defense Finance and Accounting Service Debt and Claims Management Center",
  "Defense Health Agency (DHA)",
  "Defense Information Systems Agency (DISA)",
  "Defense Intelligence Agency (DIA)",
  "Defense Logistics Agency (DLA)",
  "Defense Nuclear Facilities Safety Board (DNFSB)",
  "Defense POW/MIA Accounting Agency (DPAA)",
  "Defense Security Cooperation Agency (DSCA)",
  "Defense Technical Information Center (DTIC)",
  "Defense Threat Reduction Agency (DTRA)",
  "Delaware River Basin Commission (DRBC)",
  "Delta Regional Authority (DRA)",
  "Denali Commission",
  "Department of Agriculture (USDA)",
  "Department of Commerce (DOC)",
  "Department of Defense (DOD)",
  "Department of Education (ED)",
  "Department of Energy (DOE)",
  "Department of Energy’s Office of Science",
  "Department of Health and Human Services (HHS)",
  "Department of Homeland Security (DHS)",
  "Department of Housing and Urban Development (HUD)",
  "Department of Justice (DOJ)",
  "Department of Labor (DOL)",
  "Department of State (DOS)",
  "Department of the Interior (DOI)",
  "Department of the Treasury",
  "Department of Transportation (DOT)",
  "Department of Veterans Affairs (VA)",
  "Director of National Intelligence, Office of (ODNI)",
  "Disability Employment Policy, Office of (ODEP)",
  "Drug Enforcement Administration (DEA)",
  "Economic Analysis, Bureau of (BEA)",
  "Economic Development Administration (EDA)",
  "Economic Growth, Energy, and the Environment",
  "Economic Research Service (ERS)",
  "Education Department (ED)",
  "Elder Justice Initiative (EJI)",
  "Election Assistance Commission (EAC)",
  "Elementary and Secondary Education, Office of (OESE)",
  "Employee Benefits Security Administration (EBSA)",
  "Employment and Training Administration (ETA)",
  "Energy Department (DOE)",
  "Energy Information Administration (EIA)",
  "Engraving and Printing, Bureau of (BEP)",
  "Environmental Management, Office of",
  "Environmental Protection Agency (EPA)",
  "Equal Employment Opportunity Commission (EEOC)",
  "European Command (USEUCOM)",
  "Executive Office for Immigration Review (EOIR)",
  "Export-Import Bank of the United States (EXIM)",
  "Fair Housing and Equal Opportunity (FHEO)",
  "Fannie Mae",
  "Farm Credit Administration (FCA)",
  "Farm Credit System Insurance Corporation (FCSIC)",
  "Farm Service Agency (FSA)",
  "Federal Accounting Standards Advisory Board (FASAB)",
  "Federal Aviation Administration (FAA)",
  "Federal Bureau of Investigation (FBI)",
  "Federal Bureau of Prisons (FBOP)",
  "Federal Committee on Statistical Methodology (FCSM)",
  "Federal Communications Commission (FCC)",
  "Federal Consulting Group (FCG)",
  "Federal Deposit Insurance Corporation (FDIC)",
  "Federal Election Commission (FEC)",
  "Federal Emergency Management Agency (FEMA)",
  "Federal Energy Regulatory Commission (FERC)",
  "Federal Executive Boards (FEBs)",
  "Federal Financial Institutions Examination Council (FFIEC)",
  "Federal Financing Bank (FFB)",
  "Federal Geographic Data Committee (FGDC)",
  "Federal Highway Administration (FHWA)",
  "Federal Housing Administration (FHA)",
  "Federal Housing Finance Agency (FHFA)",
  "Federal Judicial Center",
  "Federal Labor Relations Authority (FLRA)",
  "Federal Laboratory Consortium for Technology Transfer (FLC)",
  "Federal Law Enforcement Training Centers (FLETC)",
  "Federal Library and Information Network (FEDLINK)",
  "Federal Maritime Commission (FMC)",
  "Federal Mediation and Conciliation Service (FMCS)",
  "Federal Mine Safety and Health Review Commission",
  "Federal Motor Carrier Safety Administration (FMCSA)",
  "Federal Protective Service (FPS)",
  "Federal Railroad Administration (FRA)",
  "Federal Register (OFR)",
  "Federal Reserve System",
  "Federal Retirement Thrift Investment Board (FRTIB)",
  "Federal Student Aid Information Center",
  "Federal Trade Commission (FTC)",
  "Federal Transit Administration (FTA)",
  "Federal Voting Assistance Program",
  "FedStats (FCSM)",
  "Fire Administration (USFA)",
  "Fiscal Service, Bureau of the",
  "Fish and Wildlife Service (FWS)",
  "Fleet Forces Command (USFFC)",
  "Food and Agriculture, National Institute of (NIFA)",
  "Food and Drug Administration (FDA)",
  "Food and Nutrition Service (FNS)",
  "Food Safety and Inspection Service (FSIS)",
  "Foreign Agricultural Service (FAS)",
  "Foreign Claims Settlement Commission (FCSC)",
  "Forest Service",
  "Fossil Energy (FECM)",
  "Freddie Mac",
  "Fulbright Program",
  "General Services Administration (GSA)",
  "Geological Survey (USGS)",
  "Ginnie Mae",
  "Global Media, Agency for",
  "Government Accountability Office (GAO)",
  "Government Ethics, Office of (OGE)",
  "Government Publishing Office (GPO)",
  "Harry S. Truman Scholarship Foundation",
  "Health and Human Services Department (HHS)",
  "Health Resources and Services Administration (HRSA)",
  "Helsinki Commission",
  "Holocaust Memorial Museum",
  "Homeland Security Department (DHS)",
  "Hour and Wage Division (WHD)",
  "House of Representatives",
  "House Office of Inspector General (OIG)",
  "House Office of the Clerk",
  "Housing and Urban Development, Department of (HUD)",
  "Housing Office",
  "Immigrant and Employee Rights Section (IER)",
  "Immigration and Citizenship Services (USCIS)",
  "Immigration and Customs Enforcement (ICE)",
  "Indian Affairs (BIA)",
  "Indian Arts and Crafts Board (IACB)",
  "Indian Health Service (IHS)",
  "Indo-Pacific Command (USINDOPACOM)",
  "Indoor Air Quality (IAQ)",
  "Industry and Security, Bureau of (BIS)",
  "Inspectors General (CIGIE)",
  "Institute of Education Sciences (IES)",
  "Institute of Museum and Library Services (IMLS)",
  "Inter-American Foundation (IAF)",
  "Interagency Alternative Dispute Resolution Working Group",
  "Interagency Committee for the Management of Noxious and Exotic Weeds",
  "Interior Department (DOI)",
  "Internal Revenue Service (IRS)",
  "International Development Finance Corporation (DFC)",
  "International Labor Affairs, Bureau of (ILAB)",
  "International Trade Administration (ITA)",
  "International Trade Commission (USITC)",
  "Interpol",
  "James Madison Memorial Fellowship Foundation",
  "Japan-United States Friendship Commission (JUSFC)",
  "Job Corps",
  "John F. Kennedy Center for the Performing Arts",
  "Joint Board for the Enrollment of Actuaries",
  "Joint Chiefs of Staff",
  "Joint Congressional Committee on Inaugural Ceremonies (JCCIC)",
  "Joint Fire Science Program (JFSP)",
  "Joint Forces Staff College (JFSC)",
  "Joint Program Executive Office for Chemical, Biological, Radiological and Nuclear Defense (JPEO-CBRND)",
  "Judicial Circuit Courts of Appeal",
  "Judicial Panel on Multidistrict Litigation (JPML)",
  "Justice Department (DOJ)",
  "Justice Programs, Office of (OJP)",
  "Justice Statistics, Bureau of (BJS)",
  "Juvenile Justice and Delinquency Prevention, Office of (OJJDP)",
  "Kennedy Center",
  "Labor Department (DOL)",
  "Labor Statistics, Bureau of (BLS)",
  "Land Management, Bureau of (BLM)",
  "Legal Services Corporation",
  "Library of Congress",
   "Manufactured Housing Programs, Office of (OMHP)",
  "Marine Corps",
  "Marine Mammal Commission",
  "Maritime Administration (MARAD)",
  "Marshals Service (USMS)",
  "Mediation and Conciliation Service (FMCS)",
  "Medicaid (CMS)",
  "Medicaid and CHIP Payment and Access Commission (MACPAC)",
  "Medicare (CMS)",
  "Medicare Payment Advisory Commission (MedPAC)",
  "Merit Systems Protection Board (MSPB)",
  "Middle East Broadcasting Networks",
  "Migratory Bird Conservation Commission",
  "Military Postal Service Agency (MPSA)",
  "Millennium Challenge Corporation (MCC)",
  "Mine Safety and Health Administration (MSHA)",
  "Minority Business Development Agency (MBDA)",
  "Minority Health, Office of (OMH)",
  "Mint",
  "Missile Defense Agency (MDA)",
  "Mississippi River Commission (MRC)",
  "National Aeronautics and Space Administration (NASA)",
  "National Agricultural Library (NAL)",
  "National Agricultural Statistics Service (NASS)",
  "National Archives and Records Administration (NARA)",
  "National Cancer Institute (NCI)",
  "National Capital Planning Commission (NCPC)",
  "National Cemetery Administration (NCA)",
  "National Center for Complementary and Integrative Health (NCCIH)",
  "National Constitution Center",
  "National Council on Disability (NCD)",
  "National Credit Union Administration (NCUA)",
  "National Defense University (NDU)",
  "National Endowment for the Arts (NEA)",
  "National Endowment for the Humanities (NEH)",
  "National Flood Insurance Program (NFIP)",
  "National Gallery of Art",
  "National Geospatial-Intelligence Agency (NGA)",
  "National Guard",
  "National Health Information Center (NHIC)",
  "National Heart, Lung, and Blood Institute (NHLBI)",
  "National Highway Traffic Safety Administration (NHTSA)",
  "National Indian Gaming Commission",
  "National Institute for Occupational Safety and Health (NIOSH)",
  "National Institute of Allergy and Infectious Diseases (NIAID)",
  "National Institute of Arthritis, Musculoskeletal and Skin Diseases (NIAMS)",
  "National Institute of Corrections (NIC)",
  "National Institute of Deafness and Other Communication Disorders (NIDCD)",
  "National Institute of Diabetes and Digestive and Kidney Diseases (NIDDK)",
  "National Institute of Food and Agriculture (NIFA)",
  "National Institute of Justice (NIJ)",
  "National Institute of Mental Health (NIMH)",
  "National Institute of Neurological Disorders and Stroke (NINDS)",
  "National Institute of Standards and Technology (NIST)",
  "National Institutes of Health (NIH)",
  "National Interagency Fire Center (NIFC)",
  "National Invasive Species Information Center (NISIC)",
  "National Labor Relations Board (NLRB)",
  "National Laboratories",
  "National Library of Medicine",
  "National Marine Fisheries Service",
  "National Mediation Board (NMB)",
  "National Nuclear Security Administration (NNSA)",
  "National Ocean Service",
  "National Oceanic and Atmospheric Administration (NOAA)",
  "National Park Foundation (NPF)",
  "National Park Service (NPS)",
  "National Pesticide Information Center (NPIC)",
  "National Prevention Information Network (NPIN)",
  "National Reconnaissance Office (NRO)",
  "National Science Foundation (NSF)",
  "National Security Agency (NSA)",
  "National Security Council (NSC)",
  "National Technical Information Service (NTIS)",
  "National Telecommunications and Information Administration (NTIA)",
  "National Transportation Safety Board (NTSB)",
  "National Weather Service",
  "Natural Resources Conservation Service (NRCS)",
  "Natural Resources Revenue, Office of (ONRR)",
  "Navy",
  "NOAA Fisheries",
  "Northern Border Regional Commission",
  "Northern Command (USNORTHCOM)",
  "Nuclear Energy, Office of",
  "Nuclear Regulatory Commission (NRC)",
  "Nuclear Waste Technical Review Board (NWTRB)",
  "Oak Ridge National Laboratory (ORNL)",
  "Occupational Safety and Health Administration (OSHA)",
  "Occupational Safety and Health Review Commission (OSHRC)",
  "Ocean Energy Management, Bureau of (BOEM)",
  "Office for Civil Rights, Department of Education (OCR)",
  "Office for Civil Rights, Department of Health and Human Services",
  "Office of Career, Technical, and Adult Education (OCTAE)",
  "Office of Child Support Services (OCSS)",
  "Office of Community Planning and Development (CPD)",
  "Office of Congressional Workplace Rights (OCWR)",
  "Office of Cuba Broadcasting (Radio y TV Martí)",
  "Office of Disability Employment Policy (ODEP)",
  "Office of Elementary and Secondary Education (OESE)",
  "Office of Energy Efficiency and Renewable Energy (EERE)",
  "Office of English Language Acquisition",
  "Office of Environmental Management",
  "Office of Fair Housing and Equal Opportunity (FHEO)",
  "Office of Fossil Energy and Carbon Management (FECM)",
  "Office of Government Ethics (OGE)",
  "Office of Housing",
  "Office of Immigrant and Employee Rights (IER)",
  "Office of Investor Education and Advocacy (OIEA)",
  "Office of Justice Programs (OJP)",
  "Office of Juvenile Justice and Delinquency Prevention (OJJDP)",
  "Office of Lead Hazard Control and Healthy Homes (OLHCHH)",
  "Office of Local Defense Community Cooperation",
  "Office of Management and Budget (OMB)",
  "Office of Manufactured Housing Programs (OMHP)",
  "Office of Minority Health (OMH)",
  "Office of Multifamily Housing Programs (MFH)",
  "Office of National Drug Control Policy (ONDCP)",
  "Office of Natural Resources Revenue (ONRR)",
  "Office of Nuclear Energy",
  "Office of Personnel Management (OPM)",
  "Office of Policy Development and Research (PD&R)",
  "Office of Postsecondary Education (OPE)",
  "Office of Refugee Resettlement (ORR)",
  "Office of Science and Technology Policy (OSTP)",
  "Office of Scientific and Technical Information (OSTI)",
  "Office of Servicemember Affairs",
  "Office of Special Counsel (OSC)",
  "Office of Special Education and Rehabilitative Services (OSERS)",
  "Office of Surface Mining, Reclamation and Enforcement (OSMRE)",
  "Office of Textiles and Apparel (OTEXA)",
  "Office of the Assistant Secretary for Research and Technology",
  "Office of the Comptroller of the Currency (OCC)",
  "Office of the Director of National Intelligence (ODNI)",
  "Office of the Federal Register (OFR)",
  "Office of the Pardon Attorney",
  "Office of Weights and Measures (OWM)",
  "Office on Violence Against Women (OVW)",
  "Open World Leadership Center",
  "Pacific Command (USINDOPACOM)",
  "Pardon Attorney, Office of",
  "Parent Information and Resources Center (CPIR)",
  "Parole Commission",
  "Patent and Trademark Office (USPTO)",
  "Peace Corps",
  "Pension Benefit Guaranty Corporation (PBGC)",
  "Pentagon Force Protection Agency (PFPA)",
  "Pipeline and Hazardous Materials Safety Administration (PHMSA)",
  "Policy Development and Research (PD&R)",
  "Postal Inspection Service",
  "Postal Regulatory Commission",
  "Postal Service (USPS)",
  "Postsecondary Education, Office of (OPE)",
  "President's Council on Fitness, Sports and Nutrition (PCSFN)",
  "Presidential Scholars Commission",
  "Presidio Trust",
  "Pretrial Services Agency for the District of Columbia",
  "Prevention Information Network (NPIN)",
  "Privacy and Civil Liberties Oversight Board (PCLOB)",
  "Public and Indian Housing (PIH)",
  "Radio and TV Martí (Radio y TV Martí)",
  "Radio Free Asia (RFA)",
  "Radio Free Europe and Radio Liberty (RFE/RL)",
  "Radio Sawa",
  "Railroad Retirement Board (RRB)",
  "Reclamation, Bureau of",
  "Refugee Resettlement, Office of (ORR)",
  "Rehabilitation Services Administration (RSA)",
  "Risk Management Agency (RMA)",
  "Rural Business-Cooperative Service",
  "Rural Development",
  "Rural Housing Service",
  "Rural Utilities Service (RUS)",
  "Safety and Environmental Enforcement, Bureau of (BSEE)",
  "Saint Lawrence Seaway Development Corporation (GLS)",
  "Science and Technology Policy, Office of (OSTP)",
  "Scientific and Technical Information, Office of (OSTI)",
  "Secret Service",
  "Securities and Exchange Commission (SEC)",
  "Selective Service System (SSS)",
  "Senate",
  "Sentencing Commission",
  "Servicemember Affairs, Office of",
  "Small Business Administration (SBA)",
  "Smithsonian Institution",
  "Social Security Administration (SSA)",
  "Social Security Advisory Board (SSAB)",
  "Southeastern Power Administration",
  "Southern Command (SOUTHCOM)",
  "Southwestern Power Administration",
  "Space Command",
  "Special Counsel, Office of (OSC)",
  "Special Education and Rehabilitative Services, Office of (OSERS)",
  "Special Operations Command",
  "State Department (DOS)",
  "State Justice Institute (SJI)",
  "Stennis Center for Public Service",
  "Strategic Command (USSTRATCOM)",
  "Substance Abuse and Mental Health Services Administration (SAMHSA)",
  "Supreme Court of the United States",
  "Surface Mining, Reclamation and Enforcement, Office of (OSMRE)",
  "Surface Transportation Board (STB)",
  "Susquehanna River Basin Commission (SRBC)",
  "Tax Court",
  "Tennessee Valley Authority",
  "Trade and Development Agency (USTDA)",
  "Trade Representative",
  "Transportation Department (DOT)",
  "Transportation Security Administration (TSA)",
  "Transportation Statistics, Bureau of (BTS)",
  "Treasury Department",
  "Trustee Program",
    "U.S. AbilityOne Commission",
  "U.S. Access Board",
  "U.S. Africa Command",
  "U.S. Agency for Global Media",
  "U.S. Agency for International Development (USAID)",
  "U.S. Air Force",
  "U.S. Air Force Reserve Command",
  "U.S. Arctic Research Commission (USARC)",
  "U.S. Army",
  "U.S. Army Corps of Engineers",
  "U.S. Botanic Garden",
  "U.S. Capitol Police",
  "U.S. Capitol Visitor Center",
  "U.S. Census Bureau",
  "U.S. Central Command (CENTCOM)",
  "U.S. Chemical Safety Board (CSB)",
  "U.S. Citizenship and Immigration Services (USCIS)",
  "U.S. Coast Guard (USCG)",
  "U.S. Commission of Fine Arts",
  "U.S. Commission on International Religious Freedom (USCIRF)",
  "U.S. Commodity Futures Trading Commission (CFTC)",
  "U.S. Court of Appeals for Veterans Claims",
  "U.S. Courts of Appeal",
  "U.S. Customs and Border Protection (CBP)",
  "U.S. Cyber Command",
  "U.S. Department of Agriculture (USDA)",
  "U.S. Department of Commerce (DOC)",
  "U.S. Department of Defense (DOD)",
  "U.S. Department of Education (ED)",
  "U.S. Department of Energy (DOE)",
  "U.S. Department of Health and Human Services (HHS)",
  "U.S. Department of Homeland Security (DHS)",
  "U.S. Department of Housing and Urban Development (HUD)",
  "U.S. Department of Justice (DOJ)",
  "U.S. Department of Labor (DOL)",
  "U.S. Department of State (DOS)",
  "U.S. Department of the Interior (DOI)",
  "U.S. Department of the Treasury",
  "U.S. Department of Transportation (DOT)",
  "U.S. Department of Veterans Affairs (VA)",
  "U.S. Election Assistance Commission (EAC)",
  "U.S. European Command (USEUCOM)",
  "U.S. Fire Administration (USFA)",
  "U.S. Fleet Forces Command (USFFC)",
  "U.S. Geological Survey (USGS)",
  "U.S. House of Representatives",
  "U.S. Immigration and Customs Enforcement (ICE)",
  "U.S. Indo-Pacific Command (USINDOPACOM)",
  "U.S. International Development Finance Corporation (DFC)",
  "U.S. International Trade Commission (USITC)",
  "U.S. Marine Corps",
  "U.S. Marshals Service (USMS)",
  "U.S. Military Academy, West Point",
  "U.S. Mint",
  "U.S. Mission to the United Nations (USUN)",
  "U.S. National Central Bureau - Interpol",
  "U.S. Navy",
  "U.S. Northern Command (USNORTHCOM)",
  "U.S. Nuclear Regulatory Commission (NRC)",
  "U.S. Parole Commission",
  "U.S. Patent and Trademark Office (USPTO)",
  "U.S. Postal Inspection Service",
  "U.S. Postal Service (USPS)",
  "U.S. Senate",
  "U.S. Sentencing Commission",
  "U.S. Southern Command (SOUTHCOM)",
  "U.S. Space Command",
  "U.S. Special Operations Command",
  "U.S. Strategic Command (USSTRATCOM)",
  "U.S. Trade and Development Agency (USTDA)",
  "U.S. Trade Representative",
  "U.S. Transportation Command (USTRANSCOM)",
  "U.S. Trustee Program",
  "Udall Foundation",
  "Under Secretary for Political Affairs",
  "Under Secretary for Public Diplomacy and Public Affairs",
  "Unified Combatant Commands",
  "Uniformed Services University of the Health Sciences (USU)",
  "United States Institute of Peace (USIP)",
  "United States Interagency Council on Homelessness (USICH)",
  "Veterans Affairs Department (VA)",
  "Veterans Benefits Administration (VBA)",
  "Veterans Health Administration (VHA)",
  "Veterans' Employment and Training Service (VETS)",
  "Violence Against Women, Office on (OVW)",
  "Voice of America (VOA)",
  "Wage and Hour Division (WHD)",
  "Washington Headquarters Services (WHS)",
  "Weather Service",
  "West Point Military Academy",
  "Western Area Power Administration (WAPA)",
  "White House",
  "Wireless Telecommunications Bureau (WTB)",
  "Women's Bureau",
  "Woodrow Wilson International Center for Scholars"
]
export const budgetingAuthorityOptions = [
  "$0 – $100,000",
  "$100,000 – $250,000",
  "$250,000 – $500,000",
  "$500,000 – $1,000,000",
  "$1,000,000 – $3,000,000",
  "$3,000,000 – $5,000,000",
  "$5,000,000+"
];


